# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "It runs unit tests on iPhone 15 Plus simulator"
  lane :test do
#     reset_simulators()
    run_tests(
        project: "iosApp.xcodeproj",
        scheme: "kmm_fastlaneTests",
        sdk: "iphonesimulator",
        devices: ["iPhone 15 Plus"],
        derived_data_path: "build",
    )
  end
end
#  xcodebuild -resolvePackageDependencies -scheme bank_of_loveTests -project iosApp.xcodeproj -derivedDataPath build

